# Generated by Django 6.0 on 2025-12-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('progress', 'In Progress'), ('finished', 'Finished')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
